hibernate:
  id:
    new_generator_mappings: true
management:
  endpoints:
    web:
      base-path: /registration/manage
      exposure:
        include: '*'
server:
  port: 5001
  servlet:
    context-path: /registration
spring:
  application:
    name: RentARideRegistration
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    password: rishabh
    url: jdbc:mysql://localhost:3306/rentarideDB?createDatabaseIfNotExist=true
    username: root
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  sql:
    init:
      mode: always
